version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch/data:/meili_data
    environment:
      - MEILI_MASTER_KEY=timigogogo
      - MEILI_ENV=development
  bot-service:
    build: ./telegram-bot-services/bot-service
    container_name: bot-service
    ports:
      - "10001:8080"
    depends_on:
      - meilisearch
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=timigogogo
  collection-service:
    build: ./telegram-bot-services/collection-service
    container_name: collection-service
    ports:
      - "10002:8080"
    depends_on:
      - meilisearch
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=timigogogo
  management-service:
    build: ./telegram-bot-services/management-service
    container_name: management-service
    ports:
      - "10003:8080"
    depends_on:
      - meilisearch
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=timigogogo